// Curated list of biblical proper nouns (people, places, peoples) that common
// speech-recognition engines mishear. Used by the client-side lexicon to
// fix transcription on the fly.
export const BIBLE_NAMES: readonly string[] = [
  // Patriarchs and early figures
  "Adam", "Eve", "Cain", "Abel", "Seth", "Enos", "Enoch", "Methuselah",
  "Lamech", "Noah", "Shem", "Ham", "Japheth", "Canaan", "Nimrod",
  "Terah", "Abram", "Abraham", "Sarai", "Sarah", "Hagar", "Ishmael",
  "Lot", "Isaac", "Rebekah", "Esau", "Jacob", "Israel", "Leah",
  "Rachel", "Bilhah", "Zilpah", "Reuben", "Simeon", "Levi", "Judah",
  "Dan", "Naphtali", "Gad", "Asher", "Issachar", "Zebulun", "Dinah",
  "Joseph", "Manasseh", "Ephraim", "Benjamin", "Tamar", "Perez", "Zerah",
  "Melchizedek", "Eliezer", "Laban", "Potiphar", "Asenath", "Pharaoh",

  // Exodus and wilderness
  "Moses", "Aaron", "Miriam", "Jochebed", "Zipporah", "Jethro", "Reuel",
  "Hur", "Caleb", "Joshua", "Korah", "Dathan", "Abiram", "Eleazar",
  "Phinehas", "Balaam", "Balak", "Sihon", "Og", "Amalek", "Amalekites",
  "Midian", "Midianites", "Moab", "Moabites", "Ammon", "Ammonites",
  "Edom", "Edomites", "Jeshurun", "Nehushtan",

  // Conquest, judges, kings of Israel & Judah
  "Rahab", "Achan", "Othniel", "Ehud", "Shamgar", "Deborah", "Barak",
  "Sisera", "Jael", "Gideon", "Jerubbaal", "Abimelech", "Tola", "Jair",
  "Jephthah", "Ibzan", "Elon", "Abdon", "Samson", "Delilah", "Manoah",
  "Naomi", "Ruth", "Boaz", "Obed", "Jesse", "Eli", "Hophni", "Phinehas",
  "Hannah", "Samuel", "Saul", "Jonathan", "Mephibosheth", "David",
  "Abigail", "Bathsheba", "Uriah", "Nathan", "Absalom", "Ahithophel",
  "Joab", "Abner", "Abishai", "Asahel", "Amasa", "Adonijah", "Solomon",
  "Rehoboam", "Jeroboam", "Abijah", "Asa", "Jehoshaphat", "Jehoram",
  "Joram", "Ahaziah", "Athaliah", "Joash", "Amaziah", "Uzziah", "Azariah",
  "Jotham", "Ahaz", "Hezekiah", "Manasseh", "Amon", "Josiah", "Jehoahaz",
  "Jehoiakim", "Jehoiachin", "Zedekiah", "Nadab", "Baasha", "Elah",
  "Zimri", "Omri", "Ahab", "Jezebel", "Naboth", "Ahaziah", "Jehoram",
  "Jehu", "Jehoahaz", "Joash", "Jeroboam", "Zechariah", "Shallum",
  "Menahem", "Pekahiah", "Pekah", "Hoshea", "Tirzah",

  // Prophets
  "Elijah", "Elisha", "Isaiah", "Jeremiah", "Ezekiel", "Daniel", "Hosea",
  "Joel", "Amos", "Obadiah", "Jonah", "Micah", "Nahum", "Habakkuk",
  "Zephaniah", "Haggai", "Zechariah", "Malachi", "Gad", "Iddo", "Oded",
  "Azariah", "Hanani", "Jehu", "Micaiah", "Huldah", "Uriah", "Baruch",
  "Hananiah", "Shemaiah", "Ahijah",

  // Postexilic
  "Ezra", "Nehemiah", "Zerubbabel", "Sheshbazzar", "Jeshua", "Sanballat",
  "Tobiah", "Geshem", "Esther", "Hadassah", "Mordecai", "Vashti", "Haman",
  "Ahasuerus", "Xerxes", "Artaxerxes", "Cyrus", "Darius",

  // Empires & foreign rulers
  "Assyria", "Assyrian", "Sennacherib", "Tiglath-Pileser", "Shalmaneser",
  "Sargon", "Esarhaddon", "Babylon", "Babylonian", "Nebuchadnezzar",
  "Belshazzar", "Evil-Merodach", "Nebuzaradan", "Nabopolassar",
  "Persia", "Persian", "Media", "Medes", "Greece", "Antiochus",
  "Ptolemy", "Seleucus", "Caesar", "Augustus", "Tiberius", "Claudius",
  "Nero", "Herod", "Antipas", "Agrippa", "Pilate", "Felix", "Festus",
  "Gallio", "Drusilla", "Bernice",

  // Places — books, regions, cities
  "Eden", "Pishon", "Gihon", "Hiddekel", "Tigris", "Euphrates", "Ararat",
  "Babel", "Ur", "Haran", "Shechem", "Bethel", "Mamre", "Hebron",
  "Sodom", "Gomorrah", "Admah", "Zeboiim", "Zoar", "Salem", "Moriah",
  "Beersheba", "Beer-lahai-roi", "Paddan-aram", "Mahanaim", "Peniel",
  "Goshen", "Pithom", "Rameses", "Etham", "Marah", "Elim", "Rephidim",
  "Sinai", "Horeb", "Kadesh", "Kadesh-barnea", "Pisgah", "Nebo",
  "Jericho", "Ai", "Gibeon", "Gilgal", "Shiloh", "Ebal", "Gerizim",
  "Megiddo", "Jezreel", "Carmel", "Tabor", "Bashan", "Gilead",
  "Ramoth-gilead", "Mizpah", "Ramah", "Gibeah", "Bethlehem", "Ephrath",
  "Ephrathah", "Gath", "Ashdod", "Ashkelon", "Ekron", "Gaza",
  "Philistia", "Philistine", "Philistines", "Tyre", "Sidon", "Phoenicia",
  "Damascus", "Aram", "Syria", "Nineveh", "Tarshish", "Joppa", "Ophir",
  "Sheba", "Cush", "Nubia", "Egypt", "Memphis", "Thebes", "No-Amon",
  "Susa", "Ecbatana", "Pasargadae", "Persepolis",
  "Jerusalem", "Zion", "Ophel", "Kidron", "Hinnom", "Gehenna", "Siloam",
  "Bethesda", "Gethsemane", "Golgotha", "Calvary", "Olivet", "Bethphage",
  "Bethany", "Emmaus", "Cana", "Capernaum", "Chorazin", "Bethsaida",
  "Tiberias", "Magdala", "Nazareth", "Nain", "Sychar", "Samaria",
  "Caesarea", "Caesarea-Philippi", "Antioch", "Iconium", "Lystra",
  "Derbe", "Perga", "Pamphylia", "Pisidia", "Phrygia", "Galatia",
  "Cappadocia", "Pontus", "Bithynia", "Asia", "Ephesus", "Smyrna",
  "Pergamum", "Thyatira", "Sardis", "Philadelphia", "Laodicea",
  "Hierapolis", "Colossae", "Miletus", "Troas", "Assos", "Mitylene",
  "Chios", "Samos", "Patmos", "Rhodes", "Crete", "Cyprus", "Salamis",
  "Paphos", "Macedonia", "Philippi", "Amphipolis", "Apollonia",
  "Thessalonica", "Berea", "Athens", "Corinth", "Cenchreae", "Achaia",
  "Italy", "Rome", "Puteoli", "Syracuse", "Malta", "Melita",

  // Tribes & peoples
  "Hittite", "Hittites", "Hivite", "Hivites", "Jebusite", "Jebusites",
  "Perizzite", "Perizzites", "Girgashite", "Girgashites", "Amorite",
  "Amorites", "Canaanite", "Canaanites", "Rephaim", "Anakim", "Nephilim",
  "Horites", "Kenites", "Kenizzites", "Kadmonites", "Sidonians",
  "Samaritan", "Samaritans", "Gentile", "Gentiles", "Pharisee",
  "Pharisees", "Sadducee", "Sadducees", "Essene", "Essenes",
  "Zealot", "Herodian", "Herodians", "Scribe", "Scribes",
  "Sanhedrin", "Levite", "Levites",

  // New Testament — Gospels & Acts
  "Zechariah", "Elizabeth", "Mary", "Joseph", "John", "Jesus", "Christ",
  "Messiah", "Immanuel", "Emmanuel", "Yeshua", "Simeon", "Anna",
  "Phanuel", "Magi", "Herodias", "Salome", "Andrew", "Peter", "Cephas",
  "Bartholomew", "Nathanael", "Philip", "Thomas", "Didymus", "Matthew",
  "Levi", "James", "Alphaeus", "Thaddaeus", "Lebbaeus", "Judas",
  "Iscariot", "Matthias", "Barsabbas", "Justus", "Joses", "Jude",
  "Lazarus", "Martha", "Mary", "Magdalene", "Joanna", "Susanna",
  "Salome", "Cleopas", "Bartimaeus", "Zacchaeus", "Nicodemus",
  "Joseph", "Arimathea", "Caiaphas", "Annas", "Barabbas", "Malchus",
  "Simon", "Cyrene", "Cyrenian", "Stephen", "Philip", "Cornelius",
  "Tabitha", "Dorcas", "Aeneas", "Rhoda", "Mark", "Barnabas",
  "Paul", "Saul", "Tarsus", "Ananias", "Sapphira", "Gamaliel",
  "Apollos", "Aquila", "Priscilla", "Lydia", "Eutychus", "Crispus",
  "Sosthenes", "Tyrannus", "Demetrius", "Alexander", "Erastus",
  "Trophimus", "Tychicus", "Aristarchus", "Gaius", "Sopater",
  "Secundus", "Timothy", "Titus", "Silas", "Silvanus", "Luke",
  "Onesimus", "Philemon", "Archippus", "Epaphras", "Epaphroditus",
  "Phoebe", "Junia", "Andronicus", "Rufus", "Hermes", "Olympas",
  "Tertius", "Quartus", "Onesiphorus",

  // Other figures, deities mentioned, ritual terms
  "Yahweh", "Jehovah", "Adonai", "Elohim", "Sabaoth", "Shaddai",
  "Most-High", "Holy-One", "Lamb-of-God", "Logos", "Paraclete",
  "Beelzebul", "Beelzebub", "Belial", "Leviathan", "Behemoth",
  "Rahab", "Lilith", "Azazel", "Asherah", "Ashtoreth", "Astarte",
  "Baal", "Baalim", "Dagon", "Chemosh", "Milcom", "Molech",
  "Marduk", "Bel", "Nebo", "Tammuz", "Diana", "Artemis", "Hermes",
  "Zeus", "Castor", "Pollux", "Mercurius",

  // Books of the Bible
  "Genesis", "Exodus", "Leviticus", "Numbers", "Deuteronomy",
  "Joshua", "Judges", "Ruth", "Samuel", "Kings", "Chronicles",
  "Ezra", "Nehemiah", "Esther", "Job", "Psalms", "Proverbs",
  "Ecclesiastes", "Lamentations",
  "Matthew", "Mark", "Luke", "John", "Acts", "Romans", "Corinthians",
  "Galatians", "Ephesians", "Philippians", "Colossians", "Thessalonians",
  "Timothy", "Titus", "Philemon", "Hebrews", "Peter", "Jude", "Revelation",

  // Hard-to-recognize specifics user mentioned
  "Jeshurun", "Jehoshaphat", "Nehushtan", "Habakkuk", "Zephaniah",
  "Zerubbabel", "Mephibosheth", "Hephzibah", "Tirhakah",
];

export const AHA_PATTERNS: readonly string[] = [
  "this is important",
  "really important",
  "really crucial",
  "the key here",
  "key thing",
  "the main thing",
  "the big thing",
  "this is huge",
  "this is massive",
  "what stands out",
  "what's amazing",
  "what is amazing",
  "what really matters",
  "i just realized",
  "i just noticed",
  "i now see",
  "i see now",
  "it just hit me",
  "it hits me",
  "what's powerful",
  "what is powerful",
  "powerful because",
  "powerful here",
  "really cool",
  "this is cool",
  "wait wait",
  "oh wow",
  "wow",
  "i love this",
  "i love that",
  "the lesson here",
  "the lesson is",
  "this means",
  "what this means",
  "what's interesting",
  "really interesting",
  "very interesting",
  "the core idea",
  "the heart of",
  "the point is",
  "really demonstrates",
  "demonstrates that",
  "shows us that",
  "shows me that",
  "shows that",
  "this shows",
  "what's really going on",
  "the truth is",
  "the takeaway",
  "the takeaway is",
  "i think the",
  "what god is saying",
  "god is saying",
  "what jesus is saying",
];
