/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Api
 * API specification for Logia — a Bible reading and reflection app.
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';

/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * Returns the curated list of biblical proper nouns that the client uses to correct speech-recognition output.
 * @summary Bible names lexicon
 */
export const GetLexiconResponse = zod.object({
  "names": zod.array(zod.string()),
  "ahaPatterns": zod.array(zod.string())
}).describe('A curated dictionary of biblical proper nouns plus phrase patterns marking aha moments.')


/**
 * @summary Get a Bible chapter
 */



export const GetPassageParams = zod.object({
  "book": zod.string().describe('Book name, e.g. \"Genesis\", \"1 Samuel\"'),
  "chapter": zod.number().min(1)
})

export const GetPassageResponse = zod.object({
  "book": zod.string(),
  "chapter": zod.number(),
  "translation": zod.string(),
  "verses": zod.array(zod.object({
  "verse": zod.number(),
  "text": zod.string()
}))
})


/**
 * @summary List all sessions
 */
export const listSessionsQueryLimitMax = 200;



export const ListSessionsQueryParams = zod.object({
  "limit": zod.number().min(1).max(listSessionsQueryLimitMax).optional()
})

export const ListSessionsResponseItem = zod.object({
  "id": zod.string(),
  "book": zod.string(),
  "chapter": zod.number(),
  "title": zod.string().nullish(),
  "startedAt": zod.string().datetime({"offset":true}),
  "endedAt": zod.string().datetime({"offset":true}).nullish(),
  "durationMs": zod.number(),
  "readingMs": zod.number(),
  "reflectionMs": zod.number(),
  "averageExcitement": zod.number(),
  "peakExcitement": zod.number(),
  "ahaCount": zod.number(),
  "wordCount": zod.number()
})
export const ListSessionsResponse = zod.array(ListSessionsResponseItem)


/**
 * @summary Start a new session
 */




export const CreateSessionBody = zod.object({
  "book": zod.string().min(1),
  "chapter": zod.number().min(1),
  "title": zod.string().optional()
})


/**
 * @summary List the 5 most recent sessions
 */
export const ListRecentSessionsResponseItem = zod.object({
  "id": zod.string(),
  "book": zod.string(),
  "chapter": zod.number(),
  "title": zod.string().nullish(),
  "startedAt": zod.string().datetime({"offset":true}),
  "endedAt": zod.string().datetime({"offset":true}).nullish(),
  "durationMs": zod.number(),
  "readingMs": zod.number(),
  "reflectionMs": zod.number(),
  "averageExcitement": zod.number(),
  "peakExcitement": zod.number(),
  "ahaCount": zod.number(),
  "wordCount": zod.number()
})
export const ListRecentSessionsResponse = zod.array(ListRecentSessionsResponseItem)


/**
 * @summary Get a session with all data
 */
export const GetSessionParams = zod.object({
  "id": zod.string()
})

export const GetSessionResponse = zod.object({
  "id": zod.string(),
  "book": zod.string(),
  "chapter": zod.number(),
  "title": zod.string().nullish(),
  "startedAt": zod.string().datetime({"offset":true}),
  "endedAt": zod.string().datetime({"offset":true}).nullish(),
  "durationMs": zod.number(),
  "readingMs": zod.number(),
  "reflectionMs": zod.number(),
  "averageExcitement": zod.number(),
  "peakExcitement": zod.number(),
  "ahaCount": zod.number(),
  "wordCount": zod.number()
}).and(zod.object({
  "segments": zod.array(zod.object({
  "id": zod.string(),
  "kind": zod.enum(['reading', 'reflection']),
  "text": zod.string(),
  "startedAt": zod.number().describe('ms since session start'),
  "endedAt": zod.number().describe('ms since session start'),
  "excitement": zod.number().describe('0-1 normalized excitement score'),
  "f0Mean": zod.number().nullish(),
  "f0Std": zod.number().nullish(),
  "jitter": zod.number().nullish(),
  "shimmer": zod.number().nullish(),
  "hnr": zod.number().nullish(),
  "isAha": zod.boolean(),
  "ahaPhrase": zod.string().nullish()
})),
  "ahaMoments": zod.array(zod.object({
  "id": zod.string(),
  "text": zod.string(),
  "phrase": zod.string(),
  "excitement": zod.number(),
  "timestampMs": zod.number()
}))
}))


/**
 * @summary Update a session (append transcripts, finalize, etc)
 */
export const UpdateSessionParams = zod.object({
  "id": zod.string()
})

export const UpdateSessionBody = zod.object({
  "title": zod.string().optional(),
  "endedAt": zod.string().datetime({"offset":true}).optional(),
  "appendSegments": zod.array(zod.object({
  "id": zod.string(),
  "kind": zod.enum(['reading', 'reflection']),
  "text": zod.string(),
  "startedAt": zod.number().describe('ms since session start'),
  "endedAt": zod.number().describe('ms since session start'),
  "excitement": zod.number().describe('0-1 normalized excitement score'),
  "f0Mean": zod.number().nullish(),
  "f0Std": zod.number().nullish(),
  "jitter": zod.number().nullish(),
  "shimmer": zod.number().nullish(),
  "hnr": zod.number().nullish(),
  "isAha": zod.boolean(),
  "ahaPhrase": zod.string().nullish()
})).optional(),
  "replaceSegments": zod.array(zod.object({
  "id": zod.string(),
  "kind": zod.enum(['reading', 'reflection']),
  "text": zod.string(),
  "startedAt": zod.number().describe('ms since session start'),
  "endedAt": zod.number().describe('ms since session start'),
  "excitement": zod.number().describe('0-1 normalized excitement score'),
  "f0Mean": zod.number().nullish(),
  "f0Std": zod.number().nullish(),
  "jitter": zod.number().nullish(),
  "shimmer": zod.number().nullish(),
  "hnr": zod.number().nullish(),
  "isAha": zod.boolean(),
  "ahaPhrase": zod.string().nullish()
})).optional(),
  "finalize": zod.boolean().optional().describe('Mark the session as finished and recompute aggregates.')
})

export const UpdateSessionResponse = zod.object({
  "id": zod.string(),
  "book": zod.string(),
  "chapter": zod.number(),
  "title": zod.string().nullish(),
  "startedAt": zod.string().datetime({"offset":true}),
  "endedAt": zod.string().datetime({"offset":true}).nullish(),
  "durationMs": zod.number(),
  "readingMs": zod.number(),
  "reflectionMs": zod.number(),
  "averageExcitement": zod.number(),
  "peakExcitement": zod.number(),
  "ahaCount": zod.number(),
  "wordCount": zod.number()
}).and(zod.object({
  "segments": zod.array(zod.object({
  "id": zod.string(),
  "kind": zod.enum(['reading', 'reflection']),
  "text": zod.string(),
  "startedAt": zod.number().describe('ms since session start'),
  "endedAt": zod.number().describe('ms since session start'),
  "excitement": zod.number().describe('0-1 normalized excitement score'),
  "f0Mean": zod.number().nullish(),
  "f0Std": zod.number().nullish(),
  "jitter": zod.number().nullish(),
  "shimmer": zod.number().nullish(),
  "hnr": zod.number().nullish(),
  "isAha": zod.boolean(),
  "ahaPhrase": zod.string().nullish()
})),
  "ahaMoments": zod.array(zod.object({
  "id": zod.string(),
  "text": zod.string(),
  "phrase": zod.string(),
  "excitement": zod.number(),
  "timestampMs": zod.number()
}))
}))


/**
 * @summary Delete a session
 */
export const DeleteSessionParams = zod.object({
  "id": zod.string()
})


/**
 * @summary High-level stats for the dashboard
 */
export const GetDashboardSummaryResponse = zod.object({
  "totalSessions": zod.number(),
  "totalReadingMs": zod.number(),
  "totalReflectionMs": zod.number(),
  "totalAhaMoments": zod.number(),
  "averageExcitement": zod.number(),
  "uniqueBooks": zod.number(),
  "uniqueChapters": zod.number(),
  "currentStreakDays": zod.number()
})


/**
 * @summary Aha moments across all sessions
 */
export const listAhaMomentsQueryLimitMax = 200;



export const ListAhaMomentsQueryParams = zod.object({
  "limit": zod.number().min(1).max(listAhaMomentsQueryLimitMax).optional()
})

export const ListAhaMomentsResponseItem = zod.object({
  "id": zod.string(),
  "text": zod.string(),
  "phrase": zod.string(),
  "excitement": zod.number(),
  "timestampMs": zod.number()
}).and(zod.object({
  "sessionId": zod.string(),
  "book": zod.string(),
  "chapter": zod.number(),
  "sessionStartedAt": zod.string().datetime({"offset":true})
}))
export const ListAhaMomentsResponse = zod.array(ListAhaMomentsResponseItem)


/**
 * @summary Top passages by average vocal excitement
 */
export const ListExcitedPassagesResponseItem = zod.object({
  "book": zod.string(),
  "chapter": zod.number(),
  "averageExcitement": zod.number(),
  "sessionCount": zod.number(),
  "peakExcitement": zod.number()
})
export const ListExcitedPassagesResponse = zod.array(ListExcitedPassagesResponseItem)


/**
 * @summary List original-language study notes
 */



export const ListStudyNotesQueryParams = zod.object({
  "book": zod.string().optional(),
  "chapter": zod.number().min(1).optional(),
  "q": zod.string().optional()
})

export const ListStudyNotesResponseItem = zod.object({
  "id": zod.string(),
  "topic": zod.string(),
  "language": zod.enum(['hebrew', 'aramaic', 'greek']),
  "title": zod.string(),
  "claim": zod.string(),
  "summary": zod.string(),
  "readerValue": zod.string(),
  "sourceName": zod.string(),
  "sourceUrl": zod.string(),
  "triggerPassages": zod.array(zod.string()),
  "triggerBooks": zod.array(zod.string()),
  "triggerKeywords": zod.array(zod.string()),
  "passageRefs": zod.array(zod.string()),
  "keywords": zod.array(zod.string()),
  "evidenceRefs": zod.array(zod.string()),
  "status": zod.enum(['approved', 'needs-review']),
  "reviewerNotes": zod.string().nullish(),
  "averageRating": zod.number(),
  "ratingCount": zod.number()
})
export const ListStudyNotesResponse = zod.array(ListStudyNotesResponseItem)


/**
 * @summary Rate a study note
 */
export const RateStudyNoteParams = zod.object({
  "id": zod.string()
})


export const rateStudyNoteBodyRatingMax = 5;



export const RateStudyNoteBody = zod.object({
  "clientId": zod.string().min(1),
  "rating": zod.number().min(1).max(rateStudyNoteBodyRatingMax)
})

export const RateStudyNoteResponse = zod.object({
  "id": zod.string(),
  "rating": zod.number(),
  "averageRating": zod.number(),
  "ratingCount": zod.number()
})


/**
 * @summary Update review status or reviewer notes for a study note
 */
export const UpdateStudyNoteParams = zod.object({
  "id": zod.string()
})

export const UpdateStudyNoteBody = zod.object({
  "status": zod.enum(['approved', 'needs-review']).optional(),
  "reviewerNotes": zod.string().optional()
})

export const UpdateStudyNoteResponse = zod.object({
  "id": zod.string(),
  "topic": zod.string(),
  "language": zod.enum(['hebrew', 'aramaic', 'greek']),
  "title": zod.string(),
  "claim": zod.string(),
  "summary": zod.string(),
  "readerValue": zod.string(),
  "sourceName": zod.string(),
  "sourceUrl": zod.string(),
  "triggerPassages": zod.array(zod.string()),
  "triggerBooks": zod.array(zod.string()),
  "triggerKeywords": zod.array(zod.string()),
  "passageRefs": zod.array(zod.string()),
  "keywords": zod.array(zod.string()),
  "evidenceRefs": zod.array(zod.string()),
  "status": zod.enum(['approved', 'needs-review']),
  "reviewerNotes": zod.string().nullish(),
  "averageRating": zod.number(),
  "ratingCount": zod.number()
})


/**
 * @summary Bulk import candidate study notes
 */










export const ImportStudyNotesBody = zod.object({
  "notes": zod.array(zod.object({
  "id": zod.string().min(1),
  "topic": zod.string().min(1),
  "language": zod.enum(['hebrew', 'aramaic', 'greek']),
  "title": zod.string().min(1),
  "claim": zod.string().min(1),
  "summary": zod.string().min(1),
  "readerValue": zod.string().min(1),
  "sourceName": zod.string().min(1),
  "sourceUrl": zod.string().min(1),
  "triggerPassages": zod.array(zod.string()),
  "triggerBooks": zod.array(zod.string()),
  "triggerKeywords": zod.array(zod.string()),
  "passageRefs": zod.array(zod.string()),
  "keywords": zod.array(zod.string()),
  "evidenceRefs": zod.array(zod.string()),
  "status": zod.enum(['approved', 'needs-review']),
  "reviewerNotes": zod.string().nullish()
}))
})

export const ImportStudyNotesResponse = zod.object({
  "imported": zod.number(),
  "ids": zod.array(zod.string())
})
