/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Api
 * API specification for Logia — a Bible reading and reflection app.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customFetcher } from './fetcher';
export interface HealthStatus {
  status: string;
}

export interface ErrorResponse {
  error: string;
}

/**
 * A curated dictionary of biblical proper nouns plus phrase patterns marking aha moments.
 */
export interface Lexicon {
  names: string[];
  ahaPatterns: string[];
}

export type PassageVersesItem = {
  verse: number;
  text: string;
};

export interface Passage {
  book: string;
  chapter: number;
  translation: string;
  verses: PassageVersesItem[];
}

export interface CreateSessionInput {
  /** @minLength 1 */
  book: string;
  /** @minimum 1 */
  chapter: number;
  title?: string;
}

export type TranscriptSegmentKind = typeof TranscriptSegmentKind[keyof typeof TranscriptSegmentKind];


export const TranscriptSegmentKind = {
  reading: 'reading',
  reflection: 'reflection',
} as const;

export interface TranscriptSegment {
  id: string;
  kind: TranscriptSegmentKind;
  text: string;
  /** ms since session start */
  startedAt: number;
  /** ms since session start */
  endedAt: number;
  /** 0-1 normalized excitement score */
  excitement: number;
  f0Mean?: number | null;
  f0Std?: number | null;
  jitter?: number | null;
  shimmer?: number | null;
  hnr?: number | null;
  isAha: boolean;
  ahaPhrase?: string | null;
}

export interface AhaMoment {
  id: string;
  text: string;
  phrase: string;
  excitement: number;
  timestampMs: number;
}

export type AhaMomentWithSession = AhaMoment & {
  sessionId: string;
  book: string;
  chapter: number;
  sessionStartedAt: string;
};

export interface ExcitedPassage {
  book: string;
  chapter: number;
  averageExcitement: number;
  sessionCount: number;
  peakExcitement: number;
}

export type StudyNoteLanguage = typeof StudyNoteLanguage[keyof typeof StudyNoteLanguage];


export const StudyNoteLanguage = {
  hebrew: 'hebrew',
  aramaic: 'aramaic',
  greek: 'greek',
} as const;

export type StudyNoteStatus = typeof StudyNoteStatus[keyof typeof StudyNoteStatus];


export const StudyNoteStatus = {
  approved: 'approved',
  'needs-review': 'needs-review',
} as const;

export interface StudyNote {
  id: string;
  topic: string;
  language: StudyNoteLanguage;
  title: string;
  claim: string;
  summary: string;
  readerValue: string;
  sourceName: string;
  sourceUrl: string;
  triggerPassages: string[];
  triggerBooks: string[];
  triggerKeywords: string[];
  passageRefs: string[];
  keywords: string[];
  evidenceRefs: string[];
  status: StudyNoteStatus;
  reviewerNotes?: string | null;
  averageRating: number;
  ratingCount: number;
}

export interface RateStudyNoteInput {
  /** @minLength 1 */
  clientId: string;
  /**
     * @minimum 1
     * @maximum 5
     */
  rating: number;
}

export interface CreateStudyNoteInput {
  /** @minLength 1 */
  id: string;
  /** @minLength 1 */
  topic: string;
  language: StudyNoteLanguage;
  /** @minLength 1 */
  title: string;
  /** @minLength 1 */
  claim: string;
  /** @minLength 1 */
  summary: string;
  /** @minLength 1 */
  readerValue: string;
  /** @minLength 1 */
  sourceName: string;
  /** @minLength 1 */
  sourceUrl: string;
  triggerPassages: string[];
  triggerBooks: string[];
  triggerKeywords: string[];
  passageRefs: string[];
  keywords: string[];
  evidenceRefs: string[];
  status: StudyNoteStatus;
  reviewerNotes?: string | null;
}

export interface UpdateStudyNoteInput {
  status?: StudyNoteStatus;
  reviewerNotes?: string;
}

export interface ImportStudyNotesInput {
  notes: CreateStudyNoteInput[];
}

export interface ImportStudyNotesResult {
  imported: number;
  ids: string[];
}

export interface StudyNoteRatingResult {
  id: string;
  rating: number;
  averageRating: number;
  ratingCount: number;
}

export interface SessionSummary {
  id: string;
  book: string;
  chapter: number;
  title?: string | null;
  startedAt: string;
  endedAt?: string | null;
  durationMs: number;
  readingMs: number;
  reflectionMs: number;
  averageExcitement: number;
  peakExcitement: number;
  ahaCount: number;
  wordCount: number;
}

export type Session = SessionSummary & {
  segments: TranscriptSegment[];
  ahaMoments: AhaMoment[];
};

export interface UpdateSessionInput {
  title?: string;
  endedAt?: string;
  appendSegments?: TranscriptSegment[];
  replaceSegments?: TranscriptSegment[];
  /** Mark the session as finished and recompute aggregates. */
  finalize?: boolean;
}

export interface DashboardSummary {
  totalSessions: number;
  totalReadingMs: number;
  totalReflectionMs: number;
  totalAhaMoments: number;
  averageExcitement: number;
  uniqueBooks: number;
  uniqueChapters: number;
  currentStreakDays: number;
}

export type ListSessionsParams = {
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
};

export type ListAhaMomentsParams = {
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
};

export type ListStudyNotesParams = {
book?: string;
/**
 * @minimum 1
 */
chapter?: number;
q?: string;
};

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Health check
 */
export const getHealthCheckUrl = () => {




  return `/healthz`
}

export const healthCheck = async ( options?: RequestInit): Promise<HealthStatus> => {

  return customFetcher<HealthStatus>(getHealthCheckUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthCheckQueryKey = () => {
    return [
    `/healthz`
    ] as const;
    }


export const getHealthCheckQueryOptions = <TData = Awaited<ReturnType<typeof healthCheck>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({ signal }) => healthCheck({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthCheckQueryResult = NonNullable<Awaited<ReturnType<typeof healthCheck>>>
export type HealthCheckQueryError = unknown


/**
 * @summary Health check
 */

export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetcher>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getHealthCheckQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * Returns the curated list of biblical proper nouns that the client uses to correct speech-recognition output.
 * @summary Bible names lexicon
 */
export const getGetLexiconUrl = () => {




  return `/lexicon`
}

export const getLexicon = async ( options?: RequestInit): Promise<Lexicon> => {

  return customFetcher<Lexicon>(getGetLexiconUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetLexiconQueryKey = () => {
    return [
    `/lexicon`
    ] as const;
    }


export const getGetLexiconQueryOptions = <TData = Awaited<ReturnType<typeof getLexicon>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getLexicon>>, TError, TData>, request?: SecondParameter<typeof customFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLexiconQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLexicon>>> = ({ signal }) => getLexicon({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLexicon>>, TError, TData> & { queryKey: QueryKey }
}

export type GetLexiconQueryResult = NonNullable<Awaited<ReturnType<typeof getLexicon>>>
export type GetLexiconQueryError = unknown


/**
 * @summary Bible names lexicon
 */

export function useGetLexicon<TData = Awaited<ReturnType<typeof getLexicon>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getLexicon>>, TError, TData>, request?: SecondParameter<typeof customFetcher>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetLexiconQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * @summary Get a Bible chapter
 */
export const getGetPassageUrl = (book: string,
    chapter: number,) => {




  return `/passages/${book}/${chapter}`
}

export const getPassage = async (book: string,
    chapter: number, options?: RequestInit): Promise<Passage> => {

  return customFetcher<Passage>(getGetPassageUrl(book,chapter),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPassageQueryKey = (book: string,
    chapter: number,) => {
    return [
    `/passages/${book}/${chapter}`
    ] as const;
    }


export const getGetPassageQueryOptions = <TData = Awaited<ReturnType<typeof getPassage>>, TError = ErrorResponse>(book: string,
    chapter: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPassage>>, TError, TData>, request?: SecondParameter<typeof customFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPassageQueryKey(book,chapter);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPassage>>> = ({ signal }) => getPassage(book,chapter, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(book && chapter), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPassage>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPassageQueryResult = NonNullable<Awaited<ReturnType<typeof getPassage>>>
export type GetPassageQueryError = ErrorResponse


/**
 * @summary Get a Bible chapter
 */

export function useGetPassage<TData = Awaited<ReturnType<typeof getPassage>>, TError = ErrorResponse>(
 book: string,
    chapter: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPassage>>, TError, TData>, request?: SecondParameter<typeof customFetcher>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetPassageQueryOptions(book,chapter,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * @summary List all sessions
 */
export const getListSessionsUrl = (params?: ListSessionsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/sessions?${stringifiedParams}` : `/sessions`
}

export const listSessions = async (params?: ListSessionsParams, options?: RequestInit): Promise<SessionSummary[]> => {

  return customFetcher<SessionSummary[]>(getListSessionsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListSessionsQueryKey = (params?: ListSessionsParams,) => {
    return [
    `/sessions`, ...(params ? [params] : [])
    ] as const;
    }


export const getListSessionsQueryOptions = <TData = Awaited<ReturnType<typeof listSessions>>, TError = unknown>(params?: ListSessionsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listSessions>>, TError, TData>, request?: SecondParameter<typeof customFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSessionsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSessions>>> = ({ signal }) => listSessions(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listSessions>>, TError, TData> & { queryKey: QueryKey }
}

export type ListSessionsQueryResult = NonNullable<Awaited<ReturnType<typeof listSessions>>>
export type ListSessionsQueryError = unknown


/**
 * @summary List all sessions
 */

export function useListSessions<TData = Awaited<ReturnType<typeof listSessions>>, TError = unknown>(
 params?: ListSessionsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listSessions>>, TError, TData>, request?: SecondParameter<typeof customFetcher>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListSessionsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * @summary Start a new session
 */
export const getCreateSessionUrl = () => {




  return `/sessions`
}

export const createSession = async (createSessionInput: CreateSessionInput, options?: RequestInit): Promise<Session> => {

  return customFetcher<Session>(getCreateSessionUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createSessionInput,)
  }
);}




export const getCreateSessionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSession>>, TError,{data: CreateSessionInput}, TContext>, request?: SecondParameter<typeof customFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof createSession>>, TError,{data: CreateSessionInput}, TContext> => {

const mutationKey = ['createSession'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createSession>>, {data: CreateSessionInput}> = (props) => {
          const {data} = props ?? {};

          return  createSession(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateSessionMutationResult = NonNullable<Awaited<ReturnType<typeof createSession>>>
    export type CreateSessionMutationBody = CreateSessionInput
    export type CreateSessionMutationError = unknown

    /**
 * @summary Start a new session
 */
export const useCreateSession = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSession>>, TError,{data: CreateSessionInput}, TContext>, request?: SecondParameter<typeof customFetcher>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createSession>>,
        TError,
        {data: CreateSessionInput},
        TContext
      > => {
      return useMutation(getCreateSessionMutationOptions(options));
    }

/**
 * @summary List the 5 most recent sessions
 */
export const getListRecentSessionsUrl = () => {




  return `/sessions/recent`
}

export const listRecentSessions = async ( options?: RequestInit): Promise<SessionSummary[]> => {

  return customFetcher<SessionSummary[]>(getListRecentSessionsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListRecentSessionsQueryKey = () => {
    return [
    `/sessions/recent`
    ] as const;
    }


export const getListRecentSessionsQueryOptions = <TData = Awaited<ReturnType<typeof listRecentSessions>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listRecentSessions>>, TError, TData>, request?: SecondParameter<typeof customFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListRecentSessionsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listRecentSessions>>> = ({ signal }) => listRecentSessions({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listRecentSessions>>, TError, TData> & { queryKey: QueryKey }
}

export type ListRecentSessionsQueryResult = NonNullable<Awaited<ReturnType<typeof listRecentSessions>>>
export type ListRecentSessionsQueryError = unknown


/**
 * @summary List the 5 most recent sessions
 */

export function useListRecentSessions<TData = Awaited<ReturnType<typeof listRecentSessions>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listRecentSessions>>, TError, TData>, request?: SecondParameter<typeof customFetcher>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListRecentSessionsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * @summary Get a session with all data
 */
export const getGetSessionUrl = (id: string,) => {




  return `/sessions/${id}`
}

export const getSession = async (id: string, options?: RequestInit): Promise<Session> => {

  return customFetcher<Session>(getGetSessionUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetSessionQueryKey = (id: string,) => {
    return [
    `/sessions/${id}`
    ] as const;
    }


export const getGetSessionQueryOptions = <TData = Awaited<ReturnType<typeof getSession>>, TError = ErrorResponse>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData>, request?: SecondParameter<typeof customFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSessionQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSession>>> = ({ signal }) => getSession(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData> & { queryKey: QueryKey }
}

export type GetSessionQueryResult = NonNullable<Awaited<ReturnType<typeof getSession>>>
export type GetSessionQueryError = ErrorResponse


/**
 * @summary Get a session with all data
 */

export function useGetSession<TData = Awaited<ReturnType<typeof getSession>>, TError = ErrorResponse>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData>, request?: SecondParameter<typeof customFetcher>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetSessionQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * @summary Update a session (append transcripts, finalize, etc)
 */
export const getUpdateSessionUrl = (id: string,) => {




  return `/sessions/${id}`
}

export const updateSession = async (id: string,
    updateSessionInput: UpdateSessionInput, options?: RequestInit): Promise<Session> => {

  return customFetcher<Session>(getUpdateSessionUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateSessionInput,)
  }
);}




export const getUpdateSessionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSession>>, TError,{id: string;data: UpdateSessionInput}, TContext>, request?: SecondParameter<typeof customFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof updateSession>>, TError,{id: string;data: UpdateSessionInput}, TContext> => {

const mutationKey = ['updateSession'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateSession>>, {id: string;data: UpdateSessionInput}> = (props) => {
          const {id,data} = props ?? {};

          return  updateSession(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateSessionMutationResult = NonNullable<Awaited<ReturnType<typeof updateSession>>>
    export type UpdateSessionMutationBody = UpdateSessionInput
    export type UpdateSessionMutationError = unknown

    /**
 * @summary Update a session (append transcripts, finalize, etc)
 */
export const useUpdateSession = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSession>>, TError,{id: string;data: UpdateSessionInput}, TContext>, request?: SecondParameter<typeof customFetcher>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateSession>>,
        TError,
        {id: string;data: UpdateSessionInput},
        TContext
      > => {
      return useMutation(getUpdateSessionMutationOptions(options));
    }

/**
 * @summary Delete a session
 */
export const getDeleteSessionUrl = (id: string,) => {




  return `/sessions/${id}`
}

export const deleteSession = async (id: string, options?: RequestInit): Promise<void> => {

  return customFetcher<void>(getDeleteSessionUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteSessionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSession>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteSession>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteSession'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteSession>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteSession(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteSessionMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSession>>>

    export type DeleteSessionMutationError = unknown

    /**
 * @summary Delete a session
 */
export const useDeleteSession = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSession>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetcher>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteSession>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteSessionMutationOptions(options));
    }

/**
 * @summary High-level stats for the dashboard
 */
export const getGetDashboardSummaryUrl = () => {




  return `/dashboard/summary`
}

export const getDashboardSummary = async ( options?: RequestInit): Promise<DashboardSummary> => {

  return customFetcher<DashboardSummary>(getGetDashboardSummaryUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDashboardSummaryQueryKey = () => {
    return [
    `/dashboard/summary`
    ] as const;
    }


export const getGetDashboardSummaryQueryOptions = <TData = Awaited<ReturnType<typeof getDashboardSummary>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDashboardSummary>>, TError, TData>, request?: SecondParameter<typeof customFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDashboardSummaryQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDashboardSummary>>> = ({ signal }) => getDashboardSummary({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDashboardSummary>>, TError, TData> & { queryKey: QueryKey }
}

export type GetDashboardSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof getDashboardSummary>>>
export type GetDashboardSummaryQueryError = unknown


/**
 * @summary High-level stats for the dashboard
 */

export function useGetDashboardSummary<TData = Awaited<ReturnType<typeof getDashboardSummary>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDashboardSummary>>, TError, TData>, request?: SecondParameter<typeof customFetcher>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetDashboardSummaryQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * @summary Aha moments across all sessions
 */
export const getListAhaMomentsUrl = (params?: ListAhaMomentsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/dashboard/aha-moments?${stringifiedParams}` : `/dashboard/aha-moments`
}

export const listAhaMoments = async (params?: ListAhaMomentsParams, options?: RequestInit): Promise<AhaMomentWithSession[]> => {

  return customFetcher<AhaMomentWithSession[]>(getListAhaMomentsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListAhaMomentsQueryKey = (params?: ListAhaMomentsParams,) => {
    return [
    `/dashboard/aha-moments`, ...(params ? [params] : [])
    ] as const;
    }


export const getListAhaMomentsQueryOptions = <TData = Awaited<ReturnType<typeof listAhaMoments>>, TError = unknown>(params?: ListAhaMomentsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listAhaMoments>>, TError, TData>, request?: SecondParameter<typeof customFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAhaMomentsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAhaMoments>>> = ({ signal }) => listAhaMoments(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAhaMoments>>, TError, TData> & { queryKey: QueryKey }
}

export type ListAhaMomentsQueryResult = NonNullable<Awaited<ReturnType<typeof listAhaMoments>>>
export type ListAhaMomentsQueryError = unknown


/**
 * @summary Aha moments across all sessions
 */

export function useListAhaMoments<TData = Awaited<ReturnType<typeof listAhaMoments>>, TError = unknown>(
 params?: ListAhaMomentsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listAhaMoments>>, TError, TData>, request?: SecondParameter<typeof customFetcher>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListAhaMomentsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * @summary Top passages by average vocal excitement
 */
export const getListExcitedPassagesUrl = () => {




  return `/dashboard/excited-passages`
}

export const listExcitedPassages = async ( options?: RequestInit): Promise<ExcitedPassage[]> => {

  return customFetcher<ExcitedPassage[]>(getListExcitedPassagesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListExcitedPassagesQueryKey = () => {
    return [
    `/dashboard/excited-passages`
    ] as const;
    }


export const getListExcitedPassagesQueryOptions = <TData = Awaited<ReturnType<typeof listExcitedPassages>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listExcitedPassages>>, TError, TData>, request?: SecondParameter<typeof customFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListExcitedPassagesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listExcitedPassages>>> = ({ signal }) => listExcitedPassages({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listExcitedPassages>>, TError, TData> & { queryKey: QueryKey }
}

export type ListExcitedPassagesQueryResult = NonNullable<Awaited<ReturnType<typeof listExcitedPassages>>>
export type ListExcitedPassagesQueryError = unknown


/**
 * @summary Top passages by average vocal excitement
 */

export function useListExcitedPassages<TData = Awaited<ReturnType<typeof listExcitedPassages>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listExcitedPassages>>, TError, TData>, request?: SecondParameter<typeof customFetcher>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListExcitedPassagesQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * @summary List original-language study notes
 */
export const getListStudyNotesUrl = (params?: ListStudyNotesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/study-notes?${stringifiedParams}` : `/study-notes`
}

export const listStudyNotes = async (params?: ListStudyNotesParams, options?: RequestInit): Promise<StudyNote[]> => {

  return customFetcher<StudyNote[]>(getListStudyNotesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListStudyNotesQueryKey = (params?: ListStudyNotesParams,) => {
    return [
    `/study-notes`, ...(params ? [params] : [])
    ] as const;
    }


export const getListStudyNotesQueryOptions = <TData = Awaited<ReturnType<typeof listStudyNotes>>, TError = unknown>(params?: ListStudyNotesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listStudyNotes>>, TError, TData>, request?: SecondParameter<typeof customFetcher>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListStudyNotesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listStudyNotes>>> = ({ signal }) => listStudyNotes(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listStudyNotes>>, TError, TData> & { queryKey: QueryKey }
}

export type ListStudyNotesQueryResult = NonNullable<Awaited<ReturnType<typeof listStudyNotes>>>
export type ListStudyNotesQueryError = unknown


/**
 * @summary List original-language study notes
 */

export function useListStudyNotes<TData = Awaited<ReturnType<typeof listStudyNotes>>, TError = unknown>(
 params?: ListStudyNotesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listStudyNotes>>, TError, TData>, request?: SecondParameter<typeof customFetcher>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListStudyNotesQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * @summary Rate a study note
 */
export const getRateStudyNoteUrl = (id: string,) => {




  return `/study-notes/${id}/rating`
}

export const rateStudyNote = async (id: string,
    rateStudyNoteInput: RateStudyNoteInput, options?: RequestInit): Promise<StudyNoteRatingResult> => {

  return customFetcher<StudyNoteRatingResult>(getRateStudyNoteUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      rateStudyNoteInput,)
  }
);}




export const getRateStudyNoteMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rateStudyNote>>, TError,{id: string;data: RateStudyNoteInput}, TContext>, request?: SecondParameter<typeof customFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof rateStudyNote>>, TError,{id: string;data: RateStudyNoteInput}, TContext> => {

const mutationKey = ['rateStudyNote'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof rateStudyNote>>, {id: string;data: RateStudyNoteInput}> = (props) => {
          const {id,data} = props ?? {};

          return  rateStudyNote(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RateStudyNoteMutationResult = NonNullable<Awaited<ReturnType<typeof rateStudyNote>>>
    export type RateStudyNoteMutationBody = RateStudyNoteInput
    export type RateStudyNoteMutationError = unknown

    /**
 * @summary Rate a study note
 */
export const useRateStudyNote = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rateStudyNote>>, TError,{id: string;data: RateStudyNoteInput}, TContext>, request?: SecondParameter<typeof customFetcher>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof rateStudyNote>>,
        TError,
        {id: string;data: RateStudyNoteInput},
        TContext
      > => {
      return useMutation(getRateStudyNoteMutationOptions(options));
    }

/**
 * @summary Update review status or reviewer notes for a study note
 */
export const getUpdateStudyNoteUrl = (id: string,) => {




  return `/study-notes/${id}`
}

export const updateStudyNote = async (id: string,
    updateStudyNoteInput: UpdateStudyNoteInput, options?: RequestInit): Promise<StudyNote> => {

  return customFetcher<StudyNote>(getUpdateStudyNoteUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateStudyNoteInput,)
  }
);}




export const getUpdateStudyNoteMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateStudyNote>>, TError,{id: string;data: UpdateStudyNoteInput}, TContext>, request?: SecondParameter<typeof customFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof updateStudyNote>>, TError,{id: string;data: UpdateStudyNoteInput}, TContext> => {

const mutationKey = ['updateStudyNote'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateStudyNote>>, {id: string;data: UpdateStudyNoteInput}> = (props) => {
          const {id,data} = props ?? {};

          return  updateStudyNote(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateStudyNoteMutationResult = NonNullable<Awaited<ReturnType<typeof updateStudyNote>>>
    export type UpdateStudyNoteMutationBody = UpdateStudyNoteInput
    export type UpdateStudyNoteMutationError = unknown

    /**
 * @summary Update review status or reviewer notes for a study note
 */
export const useUpdateStudyNote = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateStudyNote>>, TError,{id: string;data: UpdateStudyNoteInput}, TContext>, request?: SecondParameter<typeof customFetcher>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateStudyNote>>,
        TError,
        {id: string;data: UpdateStudyNoteInput},
        TContext
      > => {
      return useMutation(getUpdateStudyNoteMutationOptions(options));
    }

/**
 * @summary Bulk import candidate study notes
 */
export const getImportStudyNotesUrl = () => {




  return `/study-notes/import`
}

export const importStudyNotes = async (importStudyNotesInput: ImportStudyNotesInput, options?: RequestInit): Promise<ImportStudyNotesResult> => {

  return customFetcher<ImportStudyNotesResult>(getImportStudyNotesUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      importStudyNotesInput,)
  }
);}




export const getImportStudyNotesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof importStudyNotes>>, TError,{data: ImportStudyNotesInput}, TContext>, request?: SecondParameter<typeof customFetcher>}
): UseMutationOptions<Awaited<ReturnType<typeof importStudyNotes>>, TError,{data: ImportStudyNotesInput}, TContext> => {

const mutationKey = ['importStudyNotes'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof importStudyNotes>>, {data: ImportStudyNotesInput}> = (props) => {
          const {data} = props ?? {};

          return  importStudyNotes(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ImportStudyNotesMutationResult = NonNullable<Awaited<ReturnType<typeof importStudyNotes>>>
    export type ImportStudyNotesMutationBody = ImportStudyNotesInput
    export type ImportStudyNotesMutationError = unknown

    /**
 * @summary Bulk import candidate study notes
 */
export const useImportStudyNotes = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof importStudyNotes>>, TError,{data: ImportStudyNotesInput}, TContext>, request?: SecondParameter<typeof customFetcher>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof importStudyNotes>>,
        TError,
        {data: ImportStudyNotesInput},
        TContext
      > => {
      return useMutation(getImportStudyNotesMutationOptions(options));
    }
